### ISSUE TITLE
Exporting

### ISSUE THREAD

**Issue by vyeevani** [lsongx/nerfplayer-nerfstudio#8]
Currently, exporting a mesh results in: 

Traceback (most recent call last):
  File "/usr/local/bin/ns-export", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/exporter.py", line 463, in entrypoint
    tyro.cli(Commands).main()
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/exporter.py", line 343, in main
    texture_utils.export_textured_mesh(
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/exporter/texture_utils.py", line 405, in export_textured_mesh
    outputs = pipeline.model.get_outputs_for_camera_ray_bundle(camera_ray_bundle)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/models/base_model.py", line 179, in get_outputs_for_camera_ray_bundle
    outputs = self.forward(ray_bundle=ray_bundle)
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/models/base_model.py", line 142, in forward
    return self.get_outputs(ray_bundle)
  File "/content/nerfplayer-nerfstudio/nerfplayer/nerfplayer_ngp.py", line 169, in get_outputs
    field_outputs = self.field(ray_samples)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/fields/base_field.py", line 124, in forward
    density, density_embedding = self.get_density(ray_samples)
  File "/content/nerfplayer-nerfstudio/nerfplayer/nerfplayer_ngp_field.py", line 157, in get_density
    assert ray_samples.times is not None, "Time should be included in the input for NeRFPlayer"
AssertionError: Time should be included in the input for NeRFPlayer

Wondering if mesh exporting as a sequence of meshes is supported

**Comment by lsongx** [comment]
Sorry, it is not supported yet. Tracked mesh for general dynamic objects is important, but not easy. I am optimistic that there will be some new pipelines based on the recent 3DGS coming out and fortunately support tracked mesh. Volume rendering based pipelines seem to be not flexible enough.
